// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxPu3jj9xP_zBYh8k9xVlGLwtatoyZ4aQ',
    appId: '1:175209349247:web:ec947f901a91ec6ff5bf4a',
    messagingSenderId: '175209349247',
    projectId: 'pemmobile-63893',
    authDomain: 'pemmobile-63893.firebaseapp.com',
    storageBucket: 'pemmobile-63893.appspot.com',
    measurementId: 'G-787KXBW4JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2VvhF7DQKrV1c9_DZkNlyp1FE0nTVjCs',
    appId: '1:175209349247:android:8e44a39617efbdf6f5bf4a',
    messagingSenderId: '175209349247',
    projectId: 'pemmobile-63893',
    storageBucket: 'pemmobile-63893.appspot.com',
  );
}
